### ISSUE TITLE
Discrepancy on government finance (financing) chart 

### ISSUE THREAD

**Issue by laurenceford** [devinit/datahub#443] opened 2018-10-10 15:24 UTC
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
In the case of Brazil (and potentially other countries), there is a discrepancy between the positive value displayed on the chart on the left, and the negative values in the box burst on the right. Domestic.csv lists the overall value to be positive. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to Brazil's country profile
2. Scroll down to 'Government finance - Financing'

**Expected Behaviour**
The values on the left line up with those on the right

**Screenshots/GIF**

https://files.slack.com/files-pri/T0NBT5ZDM-FDB7TL89Y/image.png 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Environment/Server:**
<pre><code>
- [ ] Production
- [x] Staging
- [ ] Test
- [ ] Development
</code></pre>

Requested Delivery Date: whenever resolved

**Comment by Duncan-Knox** [comment] 2018-10-16 11:42
@akmiller01 to confirm this issue is captured within #445?

**Comment by akmiller01** [comment] 2018-10-16 12:17
Unfortunately @Duncan-Knox we won't know if #445 will fix the line chart until we pull the new data through.

**Comment by akmiller01** [comment] 2018-10-17 12:46
Now this is a duplicate of #445 with new data on staging. Something funny going on with domestic.csv aggregation.

**Comment by akmiller01** [comment] 2018-10-18 12:51
Closing as duplicate of #445 and #446

**Closed by akmiller01** 2018-10-18 12:51 UTC
