### ISSUE TITLE
Sense checks between government finance line chart totals and box-burst totals.

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#446] opened 2018-10-12 11:05 UTC
**Is your feature request related to a problem? Please describe.**

To allow the ability to check for the appearance of inconsistencies between the totals quoted in the line charts on the front-end and the totals on the box-bursts on the front-end for the government finance data shown on domestic.csv. This would be an automated check to spot inconsistencies such as those reported in #445.

**Describe the solution you'd like**

Richard Watts summarises as "can automate a check to see if the line chart total for rev,exp and financing = the boxburst, to see how wide this issue is beyond brazil"

For example: in the instance below the line chart shows 403.1 and the box-burst total (financing) shows 403.1 which is a match.

![image](https://user-images.githubusercontent.com/13347058/46865804-bec53e00-ce16-11e8-9419-8ae6c41e44c5.png)

Whilst this example would see a mis-match of 58.4 in the line chart and -25.4 in the treemap::

![image](https://user-images.githubusercontent.com/13347058/46865878-021fac80-ce17-11e8-9428-2e0da9e43969.png)

Is this possible to set-up an automated check for each country without being a too time consuming task.

**Describe alternatives you've considered**

Manually checking each boxburst and line chart for each country.

**Requested Delivery Date:** Longer-term feature request for improvement of quality assurance if can be quick to set-up, lower immediate priority because checks undertaken so far do not indicate that this issue occurs beyond Brazil.

**Comment by akmiller01** [comment] 2018-10-18 12:50
@Duncan-Knox and I found the problem was caused by non-unique node names. So I've written a script into the generation of domestic.csv that checks for duplicates and fixes them. The latest push on https://github.com/devinit/domestic_finance_2018/tree/master/output should fix this across the board when it's pulled by @Napho .

**Comment by akmiller01** [comment] 2018-10-18 13:57
@Duncan-Knox Fixed thanks to @Napho making a pull!

**Comment by Duncan-Knox** [comment] 2018-10-26 11:57
Sorry, just picked up another difference in the Brazil on from @elmetodo. There is still an inconsistency @akmiller01 we may need to continue on the debugging and sense checks work. 

![image](https://user-images.githubusercontent.com/13347058/47564939-aaa53480-d91e-11e8-88ba-7ea7113c4726.png)

**Comment by akmiller01** [comment] 2018-10-26 13:14
@Napho pushed new updates https://github.com/devinit/domestic_finance_2018/tree/master/output

**Comment by akmiller01** [comment] 2018-10-26 18:03
@edwinmp, I think I've exhausted what I can do data-wise on this problem. We may need to think of a front-end fix.

For Brazil, it's arbitrarily throwing extra nodes on the end of total-expenditure > federal-government > recurrent-expenditure even though there are no duplicate l3 recurrent-expenditure parents, and those nodes belong instead to total-expenditure > state-governments > state-governments--recurrent-expenditure. Somehow the hierarchy script is failing, even without duplicate node names...

**Comment by edwinmp** [comment] 2018-10-29 09:14
@akmiller01 updated staging. Please have another look.

**Comment by akmiller01** [comment] 2018-10-29 12:10
I think we're finally sorted. Do you want to have a look before we close this issue, @Duncan-Knox?

**Comment by Duncan-Knox** [comment] 2018-10-29 12:41
@akmiller01 the specific fix for Brazil looks sorted. I've flagged the nature of the bug with Richard and he's asking if there's the potential that this may crop up for other cases with nodes being arbitrarily thrown on the end of total-expenditure? I guess it would be quite challenging to find any from manual searching. If there's a way to capture this it may be useful.

**Comment by akmiller01** [comment] 2018-10-29 12:46
@Duncan-Knox, I just checked and Brazil is the only case where there's a duplicate level for more than one level.

**Comment by Duncan-Knox** [comment] 2018-10-29 12:56
Sounds good @akmiller01 thanks for the confirmation

**Closed** 2018-12-10 11:09 UTC
