### ISSUE TITLE
Bug on Brazil government finance boxbursts

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#445] opened 2018-10-12 10:45 UTC
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The data on the government finance box bursts for Brazil are inconsistent between the line chart and the totals presented in the box burst.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Brazil digital profile'
2. Click on 'Government revenue, financing and expenditure'
3. Scroll down to 'Financing'

**Expected Behaviour**
The sum totals on the box burst should match the sum total on the line chart. The box burst should contain all relevant elements on domestic.csv.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![previous box burst](https://user-images.githubusercontent.com/13347058/46865101-35ad0780-ce14-11e8-9852-2a792a6bdf8e.gif)

**Additional Context**
A detailed look at the raw data suggests this may not be a back-end issue. One reason for the issue seems to link to the L2_domestic_finance 'debt securities' entry. This has data showing in 2008 and 2009, then they chart does not show for 2010, then from 2011 to 2013 the L2_domestic_finance 'debt securities' data is not showing in the total and therefore impacting the grand total and layers shown.

Requested Delivery Date: mid-priority

**Comment by Duncan-Knox** [comment] 2018-10-12 15:44
Update: appears different issue for 2010 compared to 2011, 2012 and 2013 and appears to relate to source data:

Quoting @akmiller01 from Slack conversation which appears to relate to 2010 only.

I'm not sure if we can fix Brazil without changing the source data. The tree-data making script is throwing out net-external-finance because it has a 0 value, but the two children have opposite values. We can't possibly visualize a 0 value with valued children.

**Comment by Duncan-Knox** [comment] 2018-10-16 11:42
@akmiller01 @elmetodo to confirm that this issue relates to layer naming and does not need front-end fix?

**Comment by Duncan-Knox** [comment] 2018-10-16 12:45
Ok thank you @akmiller01 had got them the wrong way round!

**Comment by akmiller01** [comment] 2018-10-17 12:45
@Duncan-Knox 2010 is fixed, but even with new data the mismatch for 2011-2013 remains. It's a bit mysterious, we might need to investigate the front-end code that does the aggregation @edwinmp . Maybe it's summing all negative values?

**Comment by Duncan-Knox** [comment] 2018-10-17 13:11
@akmiller01 interesting: comparing back to the file the line chart is still correct whilst the box bursts seem to omit the levels for: 'Debt securities L2_domestic_finance' and 'Loans L2_domestic_finance' for 2011. These therefore are not included in the box burst totals.  I think the same omissions carry on into 2012, whilst in 2013 'Loans L2_domestic_finance' is included but 'Debt securities L2_domestic_finance' is not. 

One theory to check into here is that if the layers for net external finance are named the same as net domestic finance then one of them drops out? Is this possible.

**Comment by akmiller01** [comment] 2018-10-17 13:19
You're spot on, @Duncan-Knox . I think the script that makes the parent-child relationship is again getting confused when multiple cells have the same name.

**Comment by edwinmp** [comment] 2018-10-17 13:42
Apologies @Duncan-Knox @akmiller01 ... I seem to have tunnel vision. Will look into the FE side of this ASAP.

**Comment by akmiller01** [comment] 2018-10-18 12:55
Closing as duplicate of #446

**Closed by akmiller01** 2018-10-18 12:55 UTC
